### ISSUE TITLE
NameError: name 'Gtk' is not defined

### ISSUE THREAD

**Issue by amstelchen** [amstelchen/GameInfo#1]
Problem:
```
$ GameInfo
Traceback (most recent call last):
  File "/home/mic/.local/bin/GameInfo", line 8, in <module>
    sys.exit(main())
  File "/home/mic/.local/lib/python3.9/site-packages/gameinfo/__main__.py", line 5, in main
    app = Application()           
  File "/home/mic/.local/lib/python3.9/site-packages/gameinfo/GameInfo.py", line 101, in __init__
    self.updateWidgets(textPane="Tools") # was "Machine"
  File "/home/mic/.local/lib/python3.9/site-packages/gameinfo/GameInfo.py", line 111, in updateWidgets
    self.fillTreeview(textPane)
  File "/home/mic/.local/lib/python3.9/site-packages/gameinfo/GameInfo.py", line 352, in fillTreeview
    icon_theme = Gtk.IconTheme.get_default()
NameError: name 'Gtk' is not defined

$ python3
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) 
(/usr/lib/python3/dist-packages/gi/__init__.py)
```
Solution:
```
$ sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0
```

**Comment by amstelchen** [comment]
This needs PyGObject. Mentioned here: https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-getting-started
