### ISSUE TITLE
meson.build:16:15: ERROR: Unhandled python exception

### ISSUE THREAD

**Issue by amstelchen** [amstelchen/GameInfo#5]
```
$ python3.13 -m pip install dist/gameinfo-1.0.21-py3-none-any.whl
Defaulting to user installation because normal site-packages is not writeable
Processing ./dist/gameinfo-1.0.21-py3-none-any.whl
...
Collecting pygobject<4.0.0,>=3.44.1 (from gameinfo==1.0.21)
  Using cached pygobject-3.48.1.tar.gz (714 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 2
  ╰─> [77 lines of output]
      + meson setup /tmp/pip-install-lfer9h3l/pygobject_886adb06dfe54a41aac319c26b4fab18 /tmp/pip-install-lfer9h3l/pygobject_886adb06dfe54a41aac319c26b4fab18/.mesonpy-867sldse -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dtests=false -Dwheel=true --wrap-mode=nofallback --native-file=/tmp/pip-install-lfer9h3l/pygobject_886adb06dfe54a41aac319c26b4fab18/.mesonpy-867sldse/meson-python-native-file.ini
      Traceback (most recent call last):
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/mesonmain.py", line 194, in run
          return options.run_func(options)
                 ~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/msetup.py", line 358, in run
          app.generate()
          ~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/msetup.py", line 181, in generate
          return self._generate(env, capture, vslite_ctx)
                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/msetup.py", line 226, in _generate
          intr.run()
          ~~~~~~~~^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreter/interpreter.py", line 3006, in run
          super().run()
          ~~~~~~~~~~~^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 172, in run
          self.evaluate_codeblock(self.ast, start=1)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 198, in evaluate_codeblock
          raise e
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 190, in evaluate_codeblock
          self.evaluate_statement(cur)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 208, in evaluate_statement
          self.assignment(cur)
          ~~~~~~~~~~~~~~~^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 644, in assignment
          value = self.evaluate_statement(node.value)
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 210, in evaluate_statement
          return self.method_call(cur)
                 ~~~~~~~~~~~~~~~~^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 559, in method_call
          res = obj.method_call(method_name, args, kwargs)
                ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreter/interpreterobjects.py", line 830, in method_call
          ret = method(state, args, kwargs)
                ~~~~~~^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/decorators.py", line 108, in wrapped
          ret = f(*wrapped_args, **wrapped_kwargs)
                ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/decorators.py", line 260, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/interpreterbase/decorators.py", line 579, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/modules/python.py", line 515, in find_installation
          python = self._find_installation_impl(state, display_name, name_or_path, required)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/modules/python.py", line 471, in _find_installation_impl
          if python.sanity(state):
             ~~~~~~~~~~~~~^^^^^^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/modules/python.py", line 83, in sanity
          ret = super().sanity()
                ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-l8k1hihw/overlay/lib/python3.13/site-packages/mesonbuild/dependencies/python.py", line 116, in sanity
          with importlib.resources.path('mesonbuild.scripts', 'python_info.py') as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'importlib.resources' has no attribute 'path'
      The Meson build system
      Version: 1.3.2
      Source dir: /tmp/pip-install-lfer9h3l/pygobject_886adb06dfe54a41aac319c26b4fab18
      Build dir: /tmp/pip-install-lfer9h3l/pygobject_886adb06dfe54a41aac319c26b4fab18/.mesonpy-867sldse
      Build type: native build
      Project name: pygobject
      Project version: 3.48.1
      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
      C linker for the host machine: cc ld.bfd 2.35.2
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      
      ../meson.build:16:15: ERROR: Unhandled python exception
      
          This is a Meson bug and should be reported!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by amstelchen** [comment]
https://github.com/mesonbuild/meson/issues/12401
https://github.com/mesonbuild/meson/pull/12402
https://github.com/numpy/meson/pull/11
https://github.com/MineDojo/MineDojo/issues/82
